services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - ws-network
    restart: always
networks:
  ws-network:
    name: ws-network
    driver: bridge
