services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - ws-network
    restart: always
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - minio:/data
    command: server --address ":9001" --console-address ":9000" /data
    restart: always
    networks:
      - ws-network
volumes:
  minio:
networks:
  ws-network:
    name: ws-network
    driver: bridge
